// Generated by CoffeeScript 1.12.7
describe("Triad", function() {
  describe("creation", function() {
    this.triad = new Triad;
    return it("defaults to a C major triad", (function(_this) {
      return function() {
        (expect(_this.triad.pitch)).toEqual(0);
        (expect(_this.triad.acc)).toEqual(0);
        return (expect(_this.triad.type)).toEqual(0);
      };
    })(this));
  });
  describe("@fromSymbol", function() {
    it("builds a minor Triad from its symbol", (function(_this) {
      return function() {
        _this.triad = Triad.fromSymbol('C#m');
        (expect(_this.triad.pitch)).toEqual(0);
        (expect(_this.triad.acc)).toEqual(1);
        return (expect(_this.triad.type)).toEqual(1);
      };
    })(this));
    return it("builds an augmented Triad from its symbol", (function(_this) {
      return function() {
        _this.triad = Triad.fromSymbol('Ab+');
        (expect(_this.triad.pitch)).toEqual(8);
        (expect(_this.triad.acc)).toEqual(-1);
        return (expect(_this.triad.type)).toEqual(3);
      };
    })(this));
  });
  return describe(".toSymbol()", function() {
    return it("defaults to a C major triad", (function(_this) {
      return function() {
        _this.triad = new Triad;
        return (expect(_this.triad.toSymbol())).toEqual('C');
      };
    })(this));
  });
});
